name: rts_web
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  cupertino_icons: ^1.0.2
  video_player: ^2.4.10
  youtube_player_iframe: ^4.0.4
  firebase_core: ^2.17.0
  firebase_analytics: ^10.5.1
  firebase_auth: ^4.15.3
  http: ^1.1.0
  cloud_firestore: ^4.13.6
  info_popup: ^4.3.1
  flutter_advanced_drawer: ^1.3.5
  icons_flutter: ^0.0.4
  carousel_slider: ^4.2.1
  anchor_scroll_controller: ^0.4.4
  tab_container: ^2.0.0
  flutter_animated_button: ^2.0.3
  envied: ^0.5.3
  syncfusion_flutter_gauges: ^24.1.45

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  get_storage: ^2.1.1
  web_smooth_scroll: ^1.1.0
  envied_generator: ^0.5.3
  build_runner: ^2.4.7

flutter:

  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-Regular.ttf

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #