// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQ5hvDRBWyoC0uH4yOSUW-6V5Vp9cXmQk',
    appId: '1:248883859327:web:5e547401e7f0082ec1944a',
    messagingSenderId: '248883859327',
    projectId: 'rts-web-e78d3',
    authDomain: 'rts-web-e78d3.firebaseapp.com',
    storageBucket: 'rts-web-e78d3.appspot.com',
    measurementId: 'G-XJWVJ23H87',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuagyUONFWK-m15EFlcWBc2eFHyBF0CSU',
    appId: '1:248883859327:android:5ca7ec550c8c0748c1944a',
    messagingSenderId: '248883859327',
    projectId: 'rts-web-e78d3',
    storageBucket: 'rts-web-e78d3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-1WF4mxvfJbbo4HJNqaNTMhT8G6RtYWA',
    appId: '1:248883859327:ios:c189ca8b64d69d5fc1944a',
    messagingSenderId: '248883859327',
    projectId: 'rts-web-e78d3',
    storageBucket: 'rts-web-e78d3.appspot.com',
    iosBundleId: 'com.example.rtsWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-1WF4mxvfJbbo4HJNqaNTMhT8G6RtYWA',
    appId: '1:248883859327:ios:812153c8e60b796dc1944a',
    messagingSenderId: '248883859327',
    projectId: 'rts-web-e78d3',
    storageBucket: 'rts-web-e78d3.appspot.com',
    iosBundleId: 'com.example.rtsWeb.RunnerTests',
  );
}
